### ISSUE TITLE
Initialize DelphesProcessor instance without re-running Delphes

### ISSUE THREAD

**Issue by alexander-held** [johannbrehmer/madminer#184]
It would be convenient if there was a clean way to initialize an instance of `DelphesProcessor` that can be pointed to an existing `.root` file containing Delphes output. Right now, I believe the only way to do this is to fill the `DelphesProcessor.delphes_sample_filenames` and `DelphesProcessor.hepmc_sample_weight_labels` variables manually. The latter variable is needed because `DelphesProcessor.analyse_delphes_samples()` loops over it, but looking at the constructor of `DelphesProcessor` that loop should maybe be over `DelphesProcessor.benchmark_names` instead?

Use case: Testing different observable definitions and cuts without re-running Delphes.

**Comment by johannbrehmer** [comment]
Good point, goes on the to-do list.

One subtle point here is that at the best of my knowledge, the Delphes files do not contain the names of the different weights, just an unlabelled list of them. Their order is the same as in the HepMC file, but different from the LHE file. This means that the user has to provide the HepMC file in any case (but of course this does not mean that Delphes has to be run).

**Comment by johannbrehmer** [comment]
This is part of #188.

**Comment by johannbrehmer** [comment]
Merged in f39df424d9a98fc50a69e7b56d4ed0f4cf6080c1
