### ISSUE TITLE
error when run reweight by madminer.

### ISSUE THREAD

**Issue by FFFreitas** [johannbrehmer/madminer#291]
Hi, it's me again, I've been running some tutorial examples and trying to use HEL_UFO model to test some benchmark points and I noticed one odd thing that is happening on my machine.
When I run miner.run(...) for 'signal' events the madgraph reweight return an error that said I don't have allmatrix2py needed by the reweight api, but despite this it finishes and produce the .lhe files. I can loaded them normaly by the LHEProcessor and do all the selection cuts and use the analyse_samples(). 
however when I try to generate any plot or extract the fisher information I got this error from madminer:

--> 207     return matrix.dot(weights_benchmarks_T[:n_smaller])

ValueError: shapes (6,) and (1,677) not aligned: 6 (dim 0) != 1 (dim 0)

I figure out I way to work around in this issue by running again the MadGraph events in a different environment. I'm attaching the full error msgs and the logfiles from madgraph, I will keep doing more tests and will try to reproduce the error on a different machine, maybe is only related to my machine and/or environment  variables.

Cheers.

[run_01_tag_1_debug.log](https://github.com/johannbrehmer/madminer/files/2929241/run_01_tag_1_debug.log)
[error_madminer.txt](https://github.com/johannbrehmer/madminer/files/2929243/error_madminer.txt)

**Comment by johannbrehmer** [comment]
Hi,

As you pointed out, there is some issue with the MadGraph reweight feature not working (and then MadMiner does not get all the needed information).

The MadGraph reweight documentation (https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/Reweight) says that

> This module is built-in in MadGraph5_aMC@NLO.2.3.2 and later. It relies on f2py; the easiest way to install f2py is to install numpy (if not already done).

Could you check if numpy is installed in the same environment you are using to run MadGraph?

(We should update the MadMiner installation instructions to point this out, and try to raise a more meaningful warning when the necessary information isn't found in the LHE file...)

Cheers,
Johann

**Comment by FFFreitas** [comment]
Yes, numpy is instaled in my madminer and MadGraph  environments. I also tested in another machine and got the same problem. to avoid this issue I'm first seting the madminer run to only run one event and latter I edit the run card with more events and using a different env to run MG5 using ./bin/madevent in the folder created by madminer. do you think it's ok to do this? I could reproduce the results in the tutorial notebooks using this "method".

**Comment by johannbrehmer** [comment]
That should be fine. 

But maybe you can try to isolate the allmatrix2py issue. When you start MadGraph on its own (without MadMiner) and activate reweighting, does it also crash?

**Comment by johannbrehmer** [comment]
I'll close this for now since this seems to be a MadGraph setup issue.
